# Generated by Django 6.0.7 on 2026-07-31 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(default="default", max_length=50, unique=True),
                ),
                (
                    "system_prompt",
                    models.TextField(
                        default="You are a clinical-grade medical AI assistant. Answer accurately, empathetically, and safely using only the provided context. If the context is insufficient, clearly state that you do not have enough verified information to answer this query."
                    ),
                ),
                ("temperature", models.FloatField(default=0.2)),
                ("top_k_retrieval", models.IntegerField(default=3)),
                ("similarity_threshold", models.FloatField(default=0.65)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "System Configuration",
            },
        ),
        migrations.AlterModelOptions(
            name="document",
            options={"ordering": ["-uploaded_at"]},
        ),
        migrations.RemoveField(
            model_name="document",
            name="indexed",
        ),
        migrations.AddField(
            model_name="document",
            name="chunk_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="document",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("indexing", "Indexing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(upload_to="medical_docs/"),
        ),
    ]
